import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

/**
 * Настройка шрифта Geist Sans
 * Используется для основного текста интерфейса
 * Подключает латинские символы и устанавливает CSS переменную --font-geist-sans
 */
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

/**
 * Настройка шрифта Geist Mono
 * Используется для моноширинного текста (код, консоль)
 * Подключает латинские символы и устанавливает CSS переменную --font-geist-mono
 */
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/**
 * Метаданные приложения
 * Используются для SEO и отображения в браузере
 */
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Корневой layout приложения
 * Оборачивает все страницы приложения
 * Устанавливает базовые настройки HTML и подключает шрифты
 *
 * @param children - дочерние компоненты страниц
 * @returns JSX разметку корневого layout
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
